import Head from "next/head";
import Card from "~/components/Card";
import PostWizard from "~/components/PostWizard";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.posts.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-center">
        <div className="w-full max-w-2xl border-x border-slate-300 px-5">
          <PostWizard />
          {data?.map((post) => (
            <Card key={post.id} title={post.title} content={post.content} />
          ))}
        </div>
      </div>
    </>
  );
}
