import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Feed from "~/components/Feed";
import PostWizard from "~/components/PostWizard";
import { api } from "~/utils/api";

export default function Home() {
  const { isLoaded, isSignedIn } = useUser();

  api.posts.getAll.useQuery();
  if (!isLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex h-screen justify-center overflow-hidden">
        <div className="flex h-full w-full max-w-2xl flex-col border-x border-slate-300">
          {isSignedIn && <PostWizard />}
          {!isSignedIn && (
            <SignInButton>
              <button className="rounded-md bg-slate-900 px-4 py-1.5 w-max ml-5 mt-5 font-semibold text-slate-100">
                Sign in
              </button>
            </SignInButton>
          )}
          <Feed />
        </div>
      </div>
    </>
  );
}
